# Generated by Django 3.2.19 on 2023-05-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0002_auto_20230518_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighInMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macro_high', models.CharField(choices=[('HP', 'High in protein'), ('HC', 'High in carbs'), ('HF', 'High in fat')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='LowInMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macro_low', models.CharField(choices=[('LP', 'Low in protein'), ('LC', 'Low in carbs'), ('LF', 'Low in fat')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ModerateInMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macro_moderate', models.CharField(choices=[('MP', 'Moderate in protein'), ('MC', 'Moderate in carbs'), ('MF', 'Moderate in fat')], max_length=2)),
            ],
        ),
    ]
