# Generated by Django 3.2.19 on 2023-05-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0003_highinmacro_lowinmacro_moderateinmacro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HighInMacro',
        ),
        migrations.DeleteModel(
            name='LowInMacro',
        ),
        migrations.DeleteModel(
            name='ModerateInMacro',
        ),
        migrations.AddField(
            model_name='entry',
            name='highest_in',
            field=models.CharField(choices=[('HP', 'Protein'), ('HC', 'Carbs'), ('HF', 'Fat'), ('EF', '-')], default='EF', max_length=2),
        ),
        migrations.AddField(
            model_name='entry',
            name='lowest_in',
            field=models.CharField(choices=[('LP', 'Protein'), ('LC', 'Carbs'), ('LF', 'Fat'), ('EF', '-')], default='EF', max_length=2),
        ),
    ]
