# Generated by Django 3.2.19 on 2023-05-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0004_auto_20230520_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='content',
        ),
        migrations.AddField(
            model_name='entry',
            name='cooking_time',
            field=models.IntegerField(default=0, help_text='Add your cooking/preparation time in minutes'),
        ),
        migrations.AddField(
            model_name='entry',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='steps',
            field=models.TextField(blank=True),
        ),
    ]
