# Generated by Django 3.2.19 on 2023-05-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0005_auto_20230520_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='meal_type',
            field=models.CharField(choices=[('VE', 'Vegan'), ('LO', 'Vegetarian (lacto-ovo)'), ('CA', 'Carnivore'), ('PE', 'Pescitarian'), ('EF', '-')], default='EF', max_length=2),
        ),
    ]
