# Generated by Django 3.2.19 on 2023-06-01 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0007_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='likes',
        ),
        migrations.AlterField(
            model_name='comment',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipebook.entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='carbs',
            field=models.IntegerField(default=0, help_text='Add your amount in grams'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='cooking_time',
            field=models.IntegerField(default=0, help_text='Add your cooking time in minutes'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='fat',
            field=models.IntegerField(default=0, help_text='Add your amount in grams'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='highest_in',
            field=models.CharField(choices=[('Protein', 'Protein'), ('Carbs', 'Carbs'), ('Fat', 'Fat'), ('EF', '-')], default='EF', max_length=8),
        ),
        migrations.AlterField(
            model_name='entry',
            name='lowest_in',
            field=models.CharField(choices=[('Protein', 'Protein'), ('Carbs', 'Carbs'), ('Fat', 'Fat'), ('EF', '-')], default='EF', max_length=8),
        ),
        migrations.AlterField(
            model_name='entry',
            name='meal_type',
            field=models.CharField(choices=[('Vegan', 'Vegan'), ('Vegetarian (lacto-ovo)', 'Vegetarian (lacto-ovo)'), ('Carnivore', 'Carnivore'), ('Pescitarian', 'Pescitarian'), ('EF', '-')], default='EF', max_length=23),
        ),
        migrations.AlterField(
            model_name='entry',
            name='protein',
            field=models.IntegerField(default=0, help_text='Add your amount in grams'),
        ),
    ]
