# Generated by Django 3.2.19 on 2023-06-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebook', '0010_auto_20230606_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='steps',
            field=models.TextField(),
        ),
    ]
